services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: Alexander
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  mtsfinalproject:
    container_name: mtsfinalproject
    image: whoopzee1337/mtsfinalproject
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: