server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: security-service-route
        uri: lb://security-service
        predicates[0]: Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka